# Generated by Django 3.2.3 on 2021-06-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='serial_number',
            field=models.IntegerField(null=True),
        ),
    ]
